import { Provider } from "@/components/ui/provider"
import './globals.css';
import Header from "@/components/ui/Header"
import Footer from "@/components/ui/Footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
